const enum NODE_ENV {
  DEVELOPMENT = "development",
  PRODUCTION = "production",
}

const IS_NODE_ENV_PRODUCTION = process.env.NODE_ENV === NODE_ENV.PRODUCTION;

const IS_NOT_NODE_ENV_PRODUCTION = process.env.NODE_ENV !== NODE_ENV.PRODUCTION;

const IS_NODE_ENV_DEVELOPMENT = process.env.NODE_ENV === NODE_ENV.DEVELOPMENT;

const IS_NOT_NODE_ENV_DEVELOPMENT =
  process.env.NODE_ENV !== NODE_ENV.DEVELOPMENT;

export {
  IS_NODE_ENV_DEVELOPMENT,
  IS_NODE_ENV_PRODUCTION,
  IS_NOT_NODE_ENV_DEVELOPMENT,
  IS_NOT_NODE_ENV_PRODUCTION,
};
