import { IRouteItem } from "@/models/interfaces";

//TODO Get from API and persist on DB
export const gamesRoutes: Array<IRouteItem> = [
  {
    key: "NPWR11510_00",
    title: "Darksiders Warmastered Edition",
    tooltip: "Darksiders Warmastered Edition",
    path: "/games/NPWR11510_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR18041_00",
    title: "Need for Speed™ Heat",
    tooltip: "Need for Speed™ Heat",
    path: "/games/NPWR18041_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR21008_00",
    title: "Horizon Forbidden West",
    tooltip: "Horizon Forbidden West",
    path: "/games/NPWR21008_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR15897_00",
    title: "Erica",
    tooltip: "Erica",
    path: "/games/NPWR15897_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR22997_00",
    title: "A Plague Tale: Requiem",
    tooltip: "A Plague Tale: Requiem",
    path: "/games/NPWR22997_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR20569_00",
    title: "Evil West",
    tooltip: "Evil West",
    path: "/games/NPWR20569_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR12435_00",
    title: "Dragon's Dogma: Dark Arisen",
    tooltip: "Dragon's Dogma: Dark Arisen",
    path: "/games/NPWR12435_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR18449_00",
    title: "Remnant: From the Ashes",
    tooltip: "Remnant: From the Ashes",
    path: "/games/NPWR18449_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR19895_00",
    title: "NieR Replicant ver.1.22474487139...",
    tooltip: "NieR Replicant ver.1.22474487139...",
    path: "/games/NPWR19895_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR06221_00",
    title: "Grand Theft Auto V",
    tooltip: "Grand Theft Auto V",
    path: "/games/NPWR06221_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR07518_00",
    title: "STREET FIGHTER V",
    tooltip: "STREET FIGHTER V",
    path: "/games/NPWR07518_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR20188_00",
    title: "ASTRO’s PLAYROOM",
    tooltip: "ASTRO’s PLAYROOM",
    path: "/games/NPWR20188_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR20684_00",
    title: "Marvel's Spider-Man: Miles Morales",
    tooltip: "Marvel's Spider-Man: Miles Morales",
    path: "/games/NPWR20684_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11704_00",
    title: "Titanfall® 2 Trophies",
    tooltip: "Titanfall® 2 Trophies",
    path: "/games/NPWR11704_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR22859_00",
    title: "Ghost of Tsushima",
    tooltip: "Ghost of Tsushima",
    path: "/games/NPWR22859_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR22506_00",
    title: "A Plague Tale: Innocence",
    tooltip: "A Plague Tale: Innocence",
    path: "/games/NPWR22506_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR05820_00",
    title: "Hustle Kings™",
    tooltip: "Hustle Kings™",
    path: "/games/NPWR05820_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR20954_00",
    title: "Assassin's Creed® Valhalla",
    tooltip: "Assassin's Creed® Valhalla",
    path: "/games/NPWR20954_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR19842_00",
    title: "Assassin's Creed® Valhalla",
    tooltip: "Assassin's Creed® Valhalla",
    path: "/games/NPWR19842_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR05542_00",
    title: "BATMAN™: ARKHAM KNIGHT",
    tooltip: "BATMAN™: ARKHAM KNIGHT",
    path: "/games/NPWR05542_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR07810_00",
    title: "Mortal Kombat X Trophies",
    tooltip: "Mortal Kombat X Trophies",
    path: "/games/NPWR07810_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR12514_00",
    title: "Far Cry® 5",
    tooltip: "Far Cry® 5",
    path: "/games/NPWR12514_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11068_00",
    title: "Call of Duty®: Modern Warfare® Remastered",
    tooltip: "Call of Duty®: Modern Warfare® Remastered",
    path: "/games/NPWR11068_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR09395_00",
    title: "Tom Clancy’s Ghost Recon® Wildlands",
    tooltip: "Tom Clancy’s Ghost Recon® Wildlands",
    path: "/games/NPWR09395_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR12845_00",
    title: "YAKUZA KIWAMI",
    tooltip: "YAKUZA KIWAMI",
    path: "/games/NPWR12845_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR13408_00",
    title: "Uncharted: The Lost Legacy™",
    tooltip: "Uncharted: The Lost Legacy™",
    path: "/games/NPWR13408_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR09124_00",
    title: "Unravel™",
    tooltip: "Unravel™",
    path: "/games/NPWR09124_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11974_00",
    title: "Little Nightmares",
    tooltip: "Little Nightmares",
    path: "/games/NPWR11974_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11619_00",
    title: "Need for Speed™ Payback",
    tooltip: "Need for Speed™ Payback",
    path: "/games/NPWR11619_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR05335_00",
    title: "Need for Speed™ Rivals",
    tooltip: "Need for Speed™ Rivals",
    path: "/games/NPWR05335_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR05706_00",
    title: "Minecraft: PlayStation®4 Edition",
    tooltip: "Minecraft: PlayStation®4 Edition",
    path: "/games/NPWR05706_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR12518_00",
    title: "God of War",
    tooltip: "God of War",
    path: "/games/NPWR12518_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR14065_00",
    title: "SOULCALIBUR™Ⅵ",
    tooltip: "SOULCALIBUR™Ⅵ",
    path: "/games/NPWR14065_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR10264_00",
    title: "BioShock Remastered",
    tooltip: "BioShock Remastered",
    path: "/games/NPWR10264_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11556_00",
    title: "Horizon Zero Dawn",
    tooltip: "Horizon Zero Dawn",
    path: "/games/NPWR11556_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11659_00",
    title: "The Witcher 3: Wild Hunt – Complete Edition",
    tooltip: "The Witcher 3: Wild Hunt – Complete Edition",
    path: "/games/NPWR11659_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR05212_00",
    title: "WATCH_DOGS™",
    tooltip: "WATCH_DOGS™",
    path: "/games/NPWR05212_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR16566_00",
    title: "Darksiders III",
    tooltip: "Darksiders III",
    path: "/games/NPWR16566_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR09801_00",
    title: "Uncharted 3: Drake’s Deception™ Remastered",
    tooltip: "Uncharted 3: Drake’s Deception™ Remastered",
    path: "/games/NPWR09801_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR09799_00",
    title: "Uncharted 2: Among Thieves™ Remastered",
    tooltip: "Uncharted 2: Among Thieves™ Remastered",
    path: "/games/NPWR09799_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR05671_00",
    title: "Dragon Age™: Inquisition",
    tooltip: "Dragon Age™: Inquisition",
    path: "/games/NPWR05671_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR08268_00",
    title: "God of War III Remastered",
    tooltip: "God of War III Remastered",
    path: "/games/NPWR08268_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR14876_00",
    title: "Shadow of The Tomb Raider",
    tooltip: "Shadow of The Tomb Raider",
    path: "/games/NPWR14876_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR09798_00",
    title: "Uncharted: Drake’s Fortune™ Remastered",
    tooltip: "Uncharted: Drake’s Fortune™ Remastered",
    path: "/games/NPWR09798_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11453_00",
    title: "Rise of the Tomb Raider",
    tooltip: "Rise of the Tomb Raider",
    path: "/games/NPWR11453_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR10664_00",
    title: "WATCH_DOGS® 2",
    tooltip: "WATCH_DOGS® 2",
    path: "/games/NPWR10664_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR09167_00",
    title: "Marvel's Spider-Man",
    tooltip: "Marvel's Spider-Man",
    path: "/games/NPWR09167_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR05458_00",
    title: "Tomb Raider: Definitive Edition",
    tooltip: "Tomb Raider: Definitive Edition",
    path: "/games/NPWR05458_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR07028_00",
    title: "Uncharted 4: A Thief’s End™",
    tooltip: "Uncharted 4: A Thief’s End™",
    path: "/games/NPWR07028_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR06804_00",
    title: "Far Cry® 4",
    tooltip: "Far Cry® 4",
    path: "/games/NPWR06804_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR09412_00",
    title: "Red Dead Redemption 2",
    tooltip: "Red Dead Redemption 2",
    path: "/games/NPWR09412_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR04841_00",
    title: "Assassin's Creed® IV Black Flag",
    tooltip: "Assassin's Creed® IV Black Flag",
    path: "/games/NPWR04841_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR15359_00",
    title: "Control",
    tooltip: "Control",
    path: "/games/NPWR15359_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR15388_00",
    title: "Concrete Genie",
    tooltip: "Concrete Genie",
    path: "/games/NPWR15388_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR10788_00",
    title: "Call of Duty® Infinite Warfare",
    tooltip: "Call of Duty® Infinite Warfare",
    path: "/games/NPWR10788_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR12833_00",
    title: "What Remains of Edith Finch",
    tooltip: "What Remains of Edith Finch",
    path: "/games/NPWR12833_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11249_00",
    title: "N.E.R.O.",
    tooltip: "N.E.R.O.",
    path: "/games/NPWR11249_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR12653_00",
    title: "Typoman: Revised",
    tooltip: "Typoman: Revised",
    path: "/games/NPWR12653_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR14318_00",
    title: "CODE VEIN",
    tooltip: "CODE VEIN",
    path: "/games/NPWR14318_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR12592_00",
    title: "Hellblade: Senua's Sacrifice",
    tooltip: "Hellblade: Senua's Sacrifice",
    path: "/games/NPWR12592_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR06302_00",
    title: "Beyond: Two Souls™",
    tooltip: "Beyond: Two Souls™",
    path: "/games/NPWR06302_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR08193_00",
    title: "Mirror's Edge™ Catalyst",
    tooltip: "Mirror's Edge™ Catalyst",
    path: "/games/NPWR08193_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11424_00",
    title: "Assassin's Creed® Origins",
    tooltip: "Assassin's Creed® Origins",
    path: "/games/NPWR11424_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR08934_00",
    title: "Assassin's Creed® Syndicate",
    tooltip: "Assassin's Creed® Syndicate",
    path: "/games/NPWR08934_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR08801_00",
    title: "Call of Duty®: Black Ops III",
    tooltip: "Call of Duty®: Black Ops III",
    path: "/games/NPWR08801_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR06600_00",
    title: "Assassin's Creed® Unity",
    tooltip: "Assassin's Creed® Unity",
    path: "/games/NPWR06600_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR08332_00",
    title: "The Bridge",
    tooltip: "The Bridge",
    path: "/games/NPWR08332_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR16485_00",
    title: "Hollow Knight",
    tooltip: "Hollow Knight",
    path: "/games/NPWR16485_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR15015_00",
    title: "Horizon Chase Turbo",
    tooltip: "Horizon Chase Turbo",
    path: "/games/NPWR15015_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR13872_00",
    title: "DETROIT: BECOME HUMAN",
    tooltip: "DETROIT: BECOME HUMAN",
    path: "/games/NPWR13872_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR13736_00",
    title: "The Sims 4",
    tooltip: "The Sims 4",
    path: "/games/NPWR13736_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR07466_00",
    title: "Rocket League®",
    tooltip: "Rocket League®",
    path: "/games/NPWR07466_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR18604_00",
    title: "Nioh 2",
    tooltip: "Nioh 2",
    path: "/games/NPWR18604_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR13427_00",
    title: "Shadow of the Colossus",
    tooltip: "Shadow of the Colossus",
    path: "/games/NPWR13427_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR14361_00",
    title: "Assassin's Creed® Rogue Remastered",
    tooltip: "Assassin's Creed® Rogue Remastered",
    path: "/games/NPWR14361_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR06037_00",
    title: "METAL GEAR SOLID V: GROUND ZEROES",
    tooltip: "METAL GEAR SOLID V: GROUND ZEROES",
    path: "/games/NPWR06037_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR08243_00",
    title: "METAL GEAR SOLID V: THE PHANTOM PAIN",
    tooltip: "METAL GEAR SOLID V: THE PHANTOM PAIN",
    path: "/games/NPWR08243_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR15055_00",
    title: "Far Cry® 3 Classic Edition",
    tooltip: "Far Cry® 3 Classic Edition",
    path: "/games/NPWR15055_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR06071_00",
    title: "Assassin's Creed® Freedom Cry",
    tooltip: "Assassin's Creed® Freedom Cry",
    path: "/games/NPWR06071_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR07897_00",
    title: "DARK SOULS III",
    tooltip: "DARK SOULS III",
    path: "/games/NPWR07897_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR08983_00",
    title: "NieR:Automata",
    tooltip: "NieR:Automata",
    path: "/games/NPWR08983_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR08199_00",
    title: "DARK SOULS™ Ⅱ: Scholar of the First Sin",
    tooltip: "DARK SOULS™ Ⅱ: Scholar of the First Sin",
    path: "/games/NPWR08199_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR13281_00",
    title: "DARK SOULS™: REMASTERED",
    tooltip: "DARK SOULS™: REMASTERED",
    path: "/games/NPWR13281_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR05818_00",
    title: "Bloodborne",
    tooltip: "Bloodborne",
    path: "/games/NPWR05818_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR15587_00",
    title: "Sekiro™: Shadows Die Twice",
    tooltip: "Sekiro™: Shadows Die Twice",
    path: "/games/NPWR15587_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR16977_00",
    title: "Tom Clancy's Ghost Recon® Breakpoint",
    tooltip: "Tom Clancy's Ghost Recon® Breakpoint",
    path: "/games/NPWR16977_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR10261_00",
    title: "Nioh",
    tooltip: "Nioh",
    path: "/games/NPWR10261_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR13786_00",
    title: "Aer Trophy Set",
    tooltip: "Aer Trophy Set",
    path: "/games/NPWR13786_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11437_00",
    title: "Assassin's Creed® Revelations",
    tooltip: "Assassin's Creed® Revelations",
    path: "/games/NPWR11437_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11436_00",
    title: "Assassin's Creed® Brotherhood",
    tooltip: "Assassin's Creed® Brotherhood",
    path: "/games/NPWR11436_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR14916_00",
    title: "Fe",
    tooltip: "Fe",
    path: "/games/NPWR14916_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR16713_00",
    title: "Far Cry® New Dawn",
    tooltip: "Far Cry® New Dawn",
    path: "/games/NPWR16713_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR16633_00",
    title: "Assassin's Creed® Liberation Remastered",
    tooltip: "Assassin's Creed® Liberation Remastered",
    path: "/games/NPWR16633_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR15386_00",
    title: "Assassin's Creed® III Remastered",
    tooltip: "Assassin's Creed® III Remastered",
    path: "/games/NPWR15386_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR11435_00",
    title: "Assassin's Creed® II",
    tooltip: "Assassin's Creed® II",
    path: "/games/NPWR11435_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR09687_00",
    title: "Far Cry® Primal",
    tooltip: "Far Cry® Primal",
    path: "/games/NPWR09687_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR15484_00",
    title: "Gorogoa",
    tooltip: "Gorogoa",
    path: "/games/NPWR15484_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR13822_00",
    title: "Assassin's Creed® Odyssey",
    tooltip: "Assassin's Creed® Odyssey",
    path: "/games/NPWR13822_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR15235_00",
    title: "FIFA 19",
    tooltip: "FIFA 19",
    path: "/games/NPWR15235_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
  {
    key: "NPWR12997_00",
    title: "Sonic Mania",
    tooltip: "Sonic Mania",
    path: "/games/NPWR12997_00",
    component: "GameDetails",
    enabled: true,
    subRoutes: [],
    appendDivider: true,
    expanded: false,
  },
];
